import { db } from "./index";
import { categories, suppliers, products, customers, expenses, aiDecisions, users } from "./schema";
import bcrypt from "bcryptjs";

export async function seedDatabase() {
  // Check if already seeded
  const existingCategories = await db.select().from(categories).limit(1);
  if (existingCategories.length > 0) return;

  console.log("Seeding database...");

  // Admin user
  const passwordHash = await bcrypt.hash("admin123", 10);
  await db.insert(users).values([
    { name: "Admin User", email: "admin@smartstock.com", passwordHash, role: "admin" },
    { name: "Store Manager", email: "manager@smartstock.com", passwordHash: await bcrypt.hash("manager123", 10), role: "manager" },
  ]);

  // Categories
  const [dairycat, bakerycat, oilscat, producecat, beveragecat] = await db
    .insert(categories)
    .values([
      { name: "Dairy" },
      { name: "Bakery" },
      { name: "Oils & Condiments" },
      { name: "Fresh Produce" },
      { name: "Beverages" },
    ])
    .returning();

  // Suppliers
  const [sup1, sup2, sup3, sup4] = await db
    .insert(suppliers)
    .values([
      {
        name: "Al Rawabi Dairy",
        category: "Dairy",
        contactEmail: "orders@alrawabi.ae",
        contactPhone: "+971-4-123-4567",
        leadTimeDays: 3,
        paymentTerms: "Net 30",
        defectRate: "0.8",
        priceScore: 88,
        reliabilityScore: 92,
        deliveryScore: 90,
        totalSpend: "168000",
        status: "active",
      },
      {
        name: "Gulf Food Trading",
        category: "Oils & Condiments",
        contactEmail: "sales@gulffoods.ae",
        contactPhone: "+971-4-234-5678",
        leadTimeDays: 5,
        paymentTerms: "Net 45",
        defectRate: "1.2",
        priceScore: 74,
        reliabilityScore: 80,
        deliveryScore: 78,
        totalSpend: "62000",
        status: "active",
      },
      {
        name: "Fresh Produce Hub",
        category: "Fresh Produce",
        contactEmail: "orders@freshproduce.ae",
        contactPhone: "+971-4-345-6789",
        leadTimeDays: 2,
        paymentTerms: "Net 15",
        defectRate: "2.1",
        priceScore: 76,
        reliabilityScore: 72,
        deliveryScore: 80,
        totalSpend: "38600",
        status: "review",
      },
      {
        name: "Mediterranean Foods",
        category: "Oils & Condiments",
        contactEmail: "contact@medfood.ae",
        contactPhone: "+971-4-456-7890",
        leadTimeDays: 4,
        paymentTerms: "Net 30",
        defectRate: "0.5",
        priceScore: 91,
        reliabilityScore: 85,
        deliveryScore: 83,
        totalSpend: "29400",
        status: "active",
      },
    ])
    .returning();

  // Products
  await db.insert(products).values([
    {
      name: "Fresh Milk 1L",
      sku: "MLK-001",
      barcode: "6291003062956",
      brand: "Al Rawabi",
      categoryId: dairycat.id,
      supplierId: sup1.id,
      price: "5.50",
      cost: "3.20",
      stock: 142,
      minStock: 30,
      maxStock: 300,
      unit: "bottle",
      image: "🥛",
      status: "healthy",
      dailySales: "34",
      healthScore: 88,
    },
    {
      name: "Greek Yogurt 500g",
      sku: "YGT-001",
      barcode: "6291003062957",
      brand: "Al Rawabi",
      categoryId: dairycat.id,
      supplierId: sup1.id,
      price: "12.00",
      cost: "7.50",
      stock: 18,
      minStock: 20,
      maxStock: 100,
      unit: "tub",
      image: "🥛",
      status: "low_stock",
      dailySales: "8",
      healthScore: 52,
    },
    {
      name: "Extra Virgin Olive Oil 750ml",
      sku: "OIL-001",
      barcode: "6291003062958",
      brand: "Mediterranean Gold",
      categoryId: oilscat.id,
      supplierId: sup4.id,
      price: "42.00",
      cost: "28.00",
      stock: 7,
      minStock: 15,
      maxStock: 80,
      unit: "bottle",
      image: "🫒",
      status: "critical",
      dailySales: "4",
      healthScore: 28,
    },
    {
      name: "Sourdough Bread 400g",
      sku: "BRD-001",
      barcode: "6291003062959",
      brand: "Artisan Bakery",
      categoryId: bakerycat.id,
      supplierId: null,
      price: "18.00",
      cost: "9.80",
      stock: 23,
      minStock: 10,
      maxStock: 60,
      unit: "loaf",
      image: "🍞",
      status: "healthy",
      dailySales: "12",
      healthScore: 91,
    },
    {
      name: "Halloumi Cheese 250g",
      sku: "CHS-001",
      barcode: "6291003062960",
      brand: "Al Rawabi",
      categoryId: dairycat.id,
      supplierId: sup1.id,
      price: "22.00",
      cost: "13.00",
      stock: 3,
      minStock: 15,
      maxStock: 80,
      unit: "pack",
      image: "🧀",
      status: "critical",
      dailySales: "9",
      healthScore: 18,
    },
    {
      name: "Cherry Tomatoes 500g",
      sku: "TOM-001",
      barcode: "6291003062961",
      brand: "Fresh Produce Hub",
      categoryId: producecat.id,
      supplierId: sup3.id,
      price: "9.50",
      cost: "5.00",
      stock: 38,
      minStock: 20,
      maxStock: 120,
      unit: "pack",
      image: "🍅",
      status: "healthy",
      dailySales: "18",
      healthScore: 76,
    },
    {
      name: "Orange Juice 1L",
      sku: "JUC-001",
      barcode: "6291003062962",
      brand: "Al Rawabi",
      categoryId: beveragecat.id,
      supplierId: sup1.id,
      price: "11.00",
      cost: "6.50",
      stock: 0,
      minStock: 20,
      maxStock: 120,
      unit: "bottle",
      image: "🍊",
      status: "dead_stock",
      dailySales: "0",
      healthScore: 5,
    },
    {
      name: "Sunflower Oil 1.8L",
      sku: "OIL-002",
      barcode: "6291003062963",
      brand: "Gulf Foods",
      categoryId: oilscat.id,
      supplierId: sup2.id,
      price: "19.00",
      cost: "11.00",
      stock: 55,
      minStock: 20,
      maxStock: 150,
      unit: "bottle",
      image: "🌻",
      status: "healthy",
      dailySales: "7",
      healthScore: 82,
    },
  ]);

  // Customers
  await db.insert(customers).values([
    {
      name: "Sarah Al Mansouri",
      email: "sarah@example.ae",
      phone: "+971-50-111-2222",
      loyaltyTier: "platinum",
      churnRisk: "low",
      totalOrders: 47,
      totalSpend: "18420",
      ltv: "19200",
      avgOrderValue: "391",
      loyaltyPoints: 1842,
      daysSinceLastVisit: 3,
      lastVisitAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    },
    {
      name: "Khalid Al Rashidi",
      email: "khalid@example.ae",
      phone: "+971-55-222-3333",
      loyaltyTier: "gold",
      churnRisk: "medium",
      totalOrders: 23,
      totalSpend: "8760",
      ltv: "9400",
      avgOrderValue: "380",
      loyaltyPoints: 876,
      daysSinceLastVisit: 21,
      lastVisitAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
    },
    {
      name: "Fatima Zahra",
      email: "fatima@example.ae",
      phone: "+971-54-333-4444",
      loyaltyTier: "platinum",
      churnRisk: "low",
      totalOrders: 62,
      totalSpend: "14200",
      ltv: "15800",
      avgOrderValue: "229",
      loyaltyPoints: 1420,
      daysSinceLastVisit: 1,
      lastVisitAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
    {
      name: "Ahmed Hassan",
      email: "ahmed@example.ae",
      phone: "+971-52-444-5555",
      loyaltyTier: "silver",
      churnRisk: "high",
      totalOrders: 8,
      totalSpend: "3200",
      ltv: "3800",
      avgOrderValue: "400",
      loyaltyPoints: 320,
      daysSinceLastVisit: 45,
      lastVisitAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    },
    {
      name: "Layla Mohammed",
      email: "layla@example.ae",
      phone: "+971-56-555-6666",
      loyaltyTier: "gold",
      churnRisk: "low",
      totalOrders: 31,
      totalSpend: "11600",
      ltv: "12500",
      avgOrderValue: "374",
      loyaltyPoints: 1160,
      daysSinceLastVisit: 7,
      lastVisitAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    },
  ]);

  // Expenses (current month)
  const now = new Date();
  await db.insert(expenses).values([
    { name: "Al Rawabi Dairy", amount: "18400", category: "Supplier", type: "supplier", dueDay: 5, month: now.getMonth() + 1, year: now.getFullYear() },
    { name: "Gulf Food Trading", amount: "12800", category: "Supplier", type: "supplier", dueDay: 8, month: now.getMonth() + 1, year: now.getFullYear() },
    { name: "Rent — Main Branch", amount: "24000", category: "Rent", type: "fixed", dueDay: 10, month: now.getMonth() + 1, year: now.getFullYear() },
    { name: "Mediterranean Foods", amount: "8200", category: "Supplier", type: "supplier", dueDay: 18, month: now.getMonth() + 1, year: now.getFullYear() },
    { name: "Utilities", amount: "3200", category: "Utilities", type: "fixed", dueDay: 30, month: now.getMonth() + 1, year: now.getFullYear() },
    { name: "Staff Salaries", amount: "42000", category: "Payroll", type: "fixed", dueDay: 28, month: now.getMonth() + 1, year: now.getFullYear() },
    { name: "Insurance", amount: "2400", category: "Operations", type: "fixed", dueDay: 15, month: now.getMonth() + 1, year: now.getFullYear() },
  ]);

  // AI Decisions
  await db.insert(aiDecisions).values([
    {
      title: "Emergency Restock: Halloumi Cheese",
      description: "Stock at 3 units — will deplete in under 8 hours based on current velocity of 9 units/day.",
      type: "purchase",
      agent: "Inventory Agent",
      priority: "critical",
      status: "pending",
      recommendation: "Order 80 units from Al Rawabi Dairy immediately. Lead time 3 days. This prevents AED 1,584 in lost sales.",
      expectedImpact: "+AED 1,584 revenue protected",
      confidence: 95,
      risk: "low",
      dataUsed: JSON.stringify(["Current stock: 3 units", "Daily sales: 9 units/day", "Lead time: 3 days", "Price: AED 22/unit"]),
    },
    {
      title: "Price Increase Opportunity: Extra Virgin Olive Oil",
      description: "Market analysis shows competitors charge 12% more for similar quality. Your margin can be improved.",
      type: "pricing",
      agent: "Profit Agent",
      priority: "high",
      status: "pending",
      recommendation: "Increase price from AED 42 to AED 46. Expected demand reduction: 8%. Net profit increase: AED 840/month.",
      expectedImpact: "+AED 840/month profit",
      confidence: 78,
      risk: "medium",
      dataUsed: JSON.stringify(["Competitor pricing data", "Demand elasticity: 0.6", "Current margin: 33%", "Monthly volume: 120 units"]),
    },
    {
      title: "Win-Back Campaign: Ahmed Hassan",
      description: "Customer inactive for 45 days. LTV at risk: AED 3,800. Predicted churn probability: 72%.",
      type: "promotion",
      agent: "Customer Agent",
      priority: "high",
      status: "pending",
      recommendation: "Send personalized 15% discount on Dairy category (his top category). Include 200 bonus loyalty points.",
      expectedImpact: "25% recovery probability",
      confidence: 68,
      risk: "low",
      dataUsed: JSON.stringify(["Days inactive: 45", "Historical reactivation rate: 25%", "LTV: AED 3,800", "Top category: Dairy"]),
    },
    {
      title: "Bulk Purchase Discount: Sunflower Oil",
      description: "Gulf Food Trading offers 8% discount for orders above 200 units. Current monthly usage: 210 units.",
      type: "purchase",
      agent: "Procurement Agent",
      priority: "medium",
      status: "approved",
      recommendation: "Place bulk order of 200 units at AED 10.12/unit (vs normal AED 11). Saves AED 176 this cycle.",
      expectedImpact: "-AED 176 cost reduction",
      confidence: 91,
      risk: "low",
      dataUsed: JSON.stringify(["Monthly usage: 210 units", "Bulk discount: 8%", "Storage capacity: 150 units free", "Cash available: AED 28K"]),
    },
    {
      title: "Dead Stock Recovery: Orange Juice",
      description: "Orange Juice 1L has 0 daily sales for 14 days. Stock: 0. Reorder not recommended without demand review.",
      type: "inventory",
      agent: "Inventory Agent",
      priority: "medium",
      status: "rejected",
      recommendation: "Discontinue SKU JUC-001 or replace with 2L family size. Survey top customers for preference.",
      expectedImpact: "AED 320 freed capital",
      confidence: 83,
      risk: "low",
      dataUsed: JSON.stringify(["Sales last 14 days: 0", "Category trend: declining", "Customer survey: 3 requests for 2L", "Storage cost: AED 23/month"]),
    },
  ]);

  console.log("Database seeded successfully!");
}
